spring:
  datasource:
    druid1:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/druid1?serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource
    druid2:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/druid2?serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource